---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: master
  generateName: pipelinerun-pull-request-
spec:
  params:
  - name: repo-url
    value: "{{ repo_url }}"
  - name: tag-name
    value: '{{ source_branch }}'
  - name: image-full-path-with-tag
    value: quay.io/rh-ee-ksaha/test:{{ source_branch }}
  pipelineSpec:
    description: |
      this pipeline offers a typical CI/CD process, with a flow including:
      - fetching a git repository as the source
      - using buildah to build a Docker image by Dockerfile
      - pusing the built Docker image to a desired repository
      - deploying it to Kubernetes cluster
    params:
    - description: The git repository URL to clone from.
      name: repo-url
      type: string
    - description: The git tag to clone.
      name: tag-name
      type: string
    - description: The image full path to host the built image, with version tag,
        e.g. "docker.io/koustavs18/nodejs-app:latest"
      name: image-full-path-with-tag
      type: string
    tasks:
    - name: fetch-repository
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.tag-name)
      - name: deleteExisting
        value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: workspace
    - name: maven-build
      params:
      - name: GOALS
        value:
        - -B
        - -DskipTests
        - clean
        - package
      runAfter:
      - fetch-repository
      taskRef:
        params:
        - name: catalog
          value: tekton-catalog-tasks
        - name: type
          value: artifact
        - name: kind
          value: task
        - name: name
          value: maven
        - name: version
          value: "0.3"
        resolver: hub
      workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: workspace
    - name: buildah
      params:
      - name: IMAGE
        value: $(params.image-full-path-with-tag)
      - name: TLSVERIFY
        value: "false"
      - name: STORAGE_DRIVER
        value: vfs
      runAfter:
      - maven-build
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
      - name: source
        workspace: workspace
      - name: dockerconfig
        workspace: quay-cred
    workspaces:
    - name: workspace
    - name: maven-settings
    - name: empty-dir
    - name: quay-cred
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
  - configMap:
      name: maven-settings
    name: maven-settings
  - name: workspace
    persistentVolumeClaim:
      claimName: shared-workspace
  - name: quay-cred
    secret:
      secretName: quay-secret
  - emptyDir: {}
    name: empty-dir
status: {}


